### ISSUE TITLE
www no domínio

### ISSUE THREAD

**Issue by sobrinhoweb** [braziljs/sobrinho-manifesto#10]
De acordo com https://github.com/blog/315-cname-support-for-github-pages
"If your CNAME is www.example.com, we redirect example.com to www.example.com (and vice versa) as an added bonus"

Com base nisso, adicionei o www no CNAME no commit d785730ea3 mas nao deu certo.
Não sei se precisa esperar propagar ou se sobrinhei a parada =/

**Comment by sobrinhoweb** [comment]
Piorou: Agora o domínio sem www não abre, tá redirecionando pra www e dando erro.
Fato que fiz alguma merda, só não sei qual .___.

![OOOpppssss](http://media.tumblr.com/tumblr_lmwjh2QfwM1qa89vy.gif)

Imagino que tenha que mudar algo no painel do domínio, como é do Zeno assignei a issue pra ele.

**Comment by sobrinhoweb** [comment]
Pelo que li em https://help.github.com/articles/setting-up-a-custom-domain-with-pages e http://stackoverflow.com/questions/9082499/custom-domain-for-github-project-pages há 2 soluções:

1) Reverter o d785730ea3f5d40cef4eb85dafd4ff867fa45f69
**(fica sem o www)**

ou

2) 
- In your DNS manager, setup two A records. One for the root apex (@) and one for www. 
- Both point to [github's IP] 

**(fica com o www)**

**Comment by sobrinhoweb** [comment]
Reverti o d785730, agora funciona sem www, mas com www o site não abre =/

**Comment by zenorocha** [comment]
Adicionei o A value para www também.

![](http://f.cl.ly/items/191U0U3P1s3V1e0N121E/Screen%20Shot%202013-02-25%20at%2010.09.30%20AM.png) 

Assim que o DNS refletir a mudança, fechamos essa issue.

**Comment by sobrinhoweb** [comment]
Perfeito!
