### ISSUE TITLE
Site fora do ar

### ISSUE THREAD

**Issue by danilovaz** [braziljs/sobrinho-manifesto#24]
Tentei acessar sobrinhomanifesto.com.br

Alterar o link no description do repositório.

![Site fora do ar](http://s28.postimg.org/fhznjkmil/Screen_Shot_2015_02_05_at_3_15_42_PM.png)

**Comment by zenorocha** [comment]
Esse domínio não foi renovado.

https://github.com/braziljs/sobrinho-manifesto/issues/23

**Comment by danilovaz** [comment]
sim, estava falando da ulr da description :smile: agora tá show ^^

**Comment by zenorocha** [comment]
Boa! Realmente tava outdated, valeu ;D
