### ISSUE TITLE
Desabilitar Botão Direito com Alert

### ISSUE THREAD

**Issue by zenorocha** [braziljs/sobrinho-manifesto#5]

**Comment by felipenmoura** [comment]
Adicionei este aqui la ;)
com direito a "copyright" e tudo! hehe

**Comment by zenorocha** [comment]
https://github.com/braziljs/sobrinho-manifesto/commit/97eec07b408f0205e13193c6e209cf7039223a1a

**Comment by zenorocha** [comment]
Fino!

**Comment by sobrinhoweb** [comment]
O commit 46fe77b estende o bloqueio para qualquer right-click
