### ISSUE TITLE
Animação seguindo mouse

### ISSUE THREAD

**Issue by zenorocha** [braziljs/sobrinho-manifesto#6]

**Comment by bernarddeluna** [comment]
Não tem mais suporte entre os browsers... para funcionar teriamos que usar JS. Existe um plugin jQuery para isso, mas creio que não valha o custo benefício

http://jquery.kidsil.net/custom-cursor/

**Comment by keppelen** [comment]
Podemos usar Flash para poder  "trolar" mais ainda, e de uma fora bem sobrinho

**Comment by sobrinhoweb** [comment]
Tem esse maldito passarinho que todo mundo já deve ter tido a infelicidade de esbarrar pelo menos uma vez na vida.
http://floern.com/software/tripleflap

**Comment by keppelen** [comment]
hahahahhah true
