### ISSUE TITLE
Preencher conteúdo do manifesto

### ISSUE THREAD

**Issue by zenorocha** [braziljs/sobrinho-manifesto#8]
Podemos colocar logo o manifesto no site para podermos lançar =]

**Comment by sobrinhoweb** [comment]
Essa é a idéia, tava combinando ontem com o @bernarddeluna de fechar isso nesse fim de semana pra já lançar semana que vem. Não sei se termino hoje, mas até o fim do feriado termino. Quero terminar não só o texto mas todas as "features" também... ;-)

**Comment by bernarddeluna** [comment]
As features eu posso ajudar a fechar.. só o texto mesmo que eu acho bacana ser seu..

**Comment by sobrinhoweb** [comment]
Beleza, vou só commitar a issue #1 e depois foco nessa.

**Comment by zenorocha** [comment]
Isso, temos bastante brincaderinhas legais já, podemos focar no conteúdo agora e depois ir "melhorando" o código-fonte ao longo do tempo.

**Comment by sobrinhoweb** [comment]
Quase lá. Deixei 10 itens prontos, se for mesmo lançar logo já tem um conteúdo pronto.
