### ISSUE TITLE
Erros de Encoding

### ISSUE THREAD

**Issue by bernarddeluna** [braziljs/sobrinho-manifesto#9]
Acredito que os erros de encoding está prejudicando exageradamente a leitura, tirando um pouco (bastante) do tesão no projeto, pois está MJUITO dificil de ler.

Solução proposta: Deixar os erros de encoding apenas nos títulos

**Comment by sobrinhoweb** [comment]
Concordo com a tua proposta. Eu que dei mole, o chrome latest (win) e o FF 17 (ununtu) estão mostrando os charset corretos e eu esqueci completamente desse problema. Na hora de comitar a issue #8 eu levo em conta isso, especifico o charset do documento HTML e deixo errado só nos títulos.

**Comment by zenorocha** [comment]
Concordo com isso, quando parei pra ler todo manifesto isso prejudicou
muito a experiência.

Um abraço,
Zeno Rocha

---

www.zenorocha.com

2012/11/26 Rudá Almeida notifications@github.com
